<?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /tools/classplayer
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: classplayer.php	Tuesday 3rd of October 2017 11:46:20 AM	ayoola@ayoo.la $ 
*/
//	Template Content ?>
<?php if( ! Ayoola_Application::isXmlHttpRequest() && $_SERVER['HTTP_USER_AGENT'] !== Ayoola_Abstract_Viewable::$userAgent ): // Only show this if this is not a ajax call ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" dir="ltr">
<head>
<META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
<?php include_once( LAYOUT_PATH . DS . 'htmlHeader' . TPL ); ?>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body style="margin: 0;">
	<div class="Ayoola_Page_Layout_Edit_File_contentContainer">
		<div class="Ayoola_Page_Layout_Edit_File_content">
		       <div class="Ayoola_Page_Layout_Edit_File_middle">
<?php endif; ?>
				<?php
//header Begins Here

echo ( ! empty( $_d5da2e7732ed8481bf2f0f9454fc7a3f ) &&  is_object( $_d5da2e7732ed8481bf2f0f9454fc7a3f ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_d5da2e7732ed8481bf2f0f9454fc7a3f->view(), '' ) : null );

//header Ends Here
?>
				<?php
//middlebar Begins Here

//middlebar Ends Here
?>
				<?php
//leftbar Begins Here

//leftbar Ends Here
?>
				<?php
//rightbar Begins Here

//rightbar Ends Here
?>  
				<?php
//footer Begins Here

//footer Ends Here
?>
<?php if( ! Ayoola_Application::isXmlHttpRequest() && $_SERVER['HTTP_USER_AGENT'] !== Ayoola_Abstract_Viewable::$userAgent ): // Only show this if this is not a ajax call ?>
			</div>
		</div>
	</div>
<?php include_once( LAYOUT_PATH . DS . 'footerJs' . TPL ) ?>
</body>
</html>
<?php endif; ?>