<?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /tools/classplayer
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: classplayer.php	Saturday 30th of January 2021 08:39:06 PM	ayoola@ayoo.la $ 
*/
//	Template Content ?>
<?php if( ! Ayoola_Application::isXmlHttpRequest() && $_SERVER['HTTP_USER_AGENT'] !== Ayoola_Abstract_Viewable::$userAgent ): // Only show this if this is not a ajax call ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" dir="ltr">
<head>
<META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
<?php include_once( LAYOUT_PATH . DS . 'htmlHeader' . TPL ); ?>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body style="margin: 0;">
	<div class="Ayoola_Page_Layout_Edit_File_contentContainer">
		<div class="Ayoola_Page_Layout_Edit_File_content">
		    <div class="Ayoola_Page_Layout_Edit_File_middle">
				<div class="pc_container">
<?php endif; ?>
					<?php
//header /tools/classplayer Begins Here

echo ( ! empty( $_11d61e8ba20d257d844c00a0eaa5f04d ) &&  is_object( $_11d61e8ba20d257d844c00a0eaa5f04d ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_11d61e8ba20d257d844c00a0eaa5f04d->view(), '' ) : null );

//header /tools/classplayer Ends Here
?>
					<?php
//middlebar /tools/classplayer Begins Here

//middlebar /tools/classplayer Ends Here
?>
					<?php
//leftbar /tools/classplayer Begins Here

//leftbar /tools/classplayer Ends Here
?>
					<?php
//rightbar /tools/classplayer Begins Here

//rightbar /tools/classplayer Ends Here
?>  
					<?php
//footer /tools/classplayer Begins Here

//footer /tools/classplayer Ends Here
?>
<?php if( ! Ayoola_Application::isXmlHttpRequest() && $_SERVER['HTTP_USER_AGENT'] !== Ayoola_Abstract_Viewable::$userAgent ): // Only show this if this is not a ajax call ?>
				</div>
			</div>
		</div>
	</div>
<?php include_once( LAYOUT_PATH . DS . 'footerJs' . TPL ) ?>
</body>
</html>
<?php endif; ?>