<?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /404
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: 404.php	Saturday 5th of September 2020 11:06:19 PM	ayoola@ayoo.la $ 
*/
//	Template Content ?>

                    <?php 

                            //	ADDED TO CHECK WITH CACHE_DIR TOO BECAUSE OF EDITING THEME PAGES
                            //	THEY WON'T HAVE CORRECT APPDIR
                        if
                        ( 

                            $x_1599347179 = Ayoola_Filter_LayoutIdToPath::getThemeIncludeFile( 'bootstrapbasic', stripos( __FILE__, Ayoola_Application::getDomainSettings( APPLICATION_DIR ) ) !== false || stripos( __FILE__,CACHE_DIR ) !== false ? array( 'prioritize_my_copy' => true, 'multiple' => true,  ) : array( 'path_blacklist' => @array_pop( explode( PC_BASE, Ayoola_Application::getDomainSettings( APPLICATION_PATH ) ) ), 'multiple' => true ) ) 
                        )
                        {

                            if( $x_1599347179 )
                            foreach( $x_1599347179 as $each )
                            {	
                                include_once $each;
                            }
                        }

                    ?>
                     <?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /layout/bootstrapbasic/template
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: template.php	Monday 19th of August 2019 07:23:16 PM	ayoola@ayoo.la $ 
*/
//	Template Content ?>
<!DOCTYPE html>
<html lang="en">
<head>
<?php include_once( LAYOUT_PATH . DS . 'htmlHeader' . TPL ) ?>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="author" content="">
<!-- Bootstrap Core CSS --><link href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/bootstrapbasic/css/bootstrap.min.css" rel="stylesheet">
<!-- Custom CSS --><link href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/bootstrapbasic/css/small-business.css" rel="stylesheet">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries --><!-- WARNING: Respond.js doesn't work if you view the page via file:// --><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]--><link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>
<body style="background-color: #ddd;" data-pc-section-name="body">
<?php include_once( LAYOUT_PATH . DS . 'header' . TPL ) ?>

    <!-- Navigation -->
<nav id="mainnav" class="navbar navbar-inverse navbar-fixed-top" role="navigation" data-pc-menu-id-list=",bs-example-navbar-collapse-1" data-pc-menu-ul-class-bs-example-navbar-collapse-1="nav navbar-nav navbar-right" data-pc-menu-li-active-class-bs-example-navbar-collapse-1="dropdown" data-pc-menu-li-ul-class-bs-example-navbar-collapse-1="dropdown-menu"><div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar">&nbsp;</span>
                    <span class="icon-bar">&nbsp;</span>
                    <span class="icon-bar">&nbsp;</span>
                </button>
                <a class="navbar-brand" style="height:auto;height:initial;height:unset;" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/"><img style="max-height:50px;" name="pc-logo" src="<?php echo Ayoola_Doc::getLogo(); ?>"></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <?php echo Ayoola_Menu_Demo::viewInLine( array( 'option' => 'mainnav', 'li-active-class' => 'dropdown', 'ul-class' => 'nav navbar-nav navbar-right', 'ul-id' => '', )  ); ?>
</div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav><!-- Page Content --><div class="xcontainer" data-pc-section-autonamed="1" data-pc-section-name="pc-body-1">

        <!-- Heading Row -->
        
<?php
//pc_body_1 Begins Here

echo ( ! empty( $_37de1278686bad05803e50ef40b938dc ) &&  is_object( $_37de1278686bad05803e50ef40b938dc ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_37de1278686bad05803e50ef40b938dc->view(), '' ) : null );

//pc_body_1 Ends Here
?><?php
//pc_body_1 /404 Begins Here

//pc_body_1 /404 Ends Here
?>


<?php
//oneness Begins Here

//oneness Ends Here
?><?php
//oneness /404 Begins Here

//oneness /404 Ends Here
?><section data-pc-all-sections="1" class="container">	
									<div class="">
										<div class="row">
											<div class="pc_page_layout_grid col-md-12 12u">
												<?php
//middlebar Begins Here

//middlebar Ends Here
?><?php
//middlebar /404 Begins Here

echo ( ! empty( $_839ecb3efc70cb6eb1bbb7b7f8b29574 ) &&  is_object( $_839ecb3efc70cb6eb1bbb7b7f8b29574 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_839ecb3efc70cb6eb1bbb7b7f8b29574->view(), 'well' ) : null );

echo ( ! empty( $_c7269e6f48bd5c84816662981df32805 ) &&  is_object( $_c7269e6f48bd5c84816662981df32805 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_c7269e6f48bd5c84816662981df32805->view(), 'white-background' ) : null );

echo ( ! empty( $_6f2ca00dd66ccaf3d4af877d389f74c4 ) &&  is_object( $_6f2ca00dd66ccaf3d4af877d389f74c4 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_6f2ca00dd66ccaf3d4af877d389f74c4->view(), '' ) : null );

//middlebar /404 Ends Here
?>
										   </div>
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-6 6u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//twosome1 Begins Here

//twosome1 Ends Here
?><?php
//twosome1 /404 Begins Here

//twosome1 /404 Ends Here
?>
											</div>
											<div class="pc_page_layout_grid col-sm-6 6u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//twosome2 Begins Here

//twosome2 Ends Here
?><?php
//twosome2 /404 Begins Here

//twosome2 /404 Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)"> 
												<?php
//threesome1 Begins Here

//threesome1 Ends Here
?><?php
//threesome1 /404 Begins Here

//threesome1 /404 Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//threesome2 Begins Here

//threesome2 Ends Here
?><?php
//threesome2 /404 Begins Here

//threesome2 /404 Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//threesome3 Begins Here

//threesome3 Ends Here
?><?php
//threesome3 /404 Begins Here

//threesome3 /404 Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome1 Begins Here

//foursome1 Ends Here
?><?php
//foursome1 /404 Begins Here

//foursome1 /404 Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome2 Begins Here

//foursome2 Ends Here
?><?php
//foursome2 /404 Begins Here

//foursome2 /404 Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-3 3u 6u(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome3 Begins Here

//foursome3 Ends Here
?><?php
//foursome3 /404 Begins Here

//foursome3 /404 Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">    
												<?php
//foursome4 Begins Here

//foursome4 Ends Here
?><?php
//foursome4 /404 Begins Here

//foursome4 /404 Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//leftbar Begins Here

//leftbar Ends Here
?><?php
//leftbar /404 Begins Here

//leftbar /404 Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-8 8u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//leftbarright Begins Here

//leftbarright Ends Here
?><?php
//leftbarright /404 Begins Here

//leftbarright /404 Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-8 8u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//rightbarleft Begins Here

//rightbarleft Ends Here
?><?php
//rightbarleft /404 Begins Here

//rightbarleft /404 Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//rightbar Begins Here

//rightbar Ends Here
?><?php
//rightbar /404 Begins Here

//rightbar /404 Ends Here
?>
											</div>   
										</div> 
									</div> 
								</section><?php
//lastoneness Begins Here

//lastoneness Ends Here
?><?php
//lastoneness /404 Begins Here

//lastoneness /404 Ends Here
?>
        <!-- /.row -->

        <hr>
<!-- Call to Action Well -->
<?php
//pc_body_2 Begins Here

//pc_body_2 Ends Here
?><?php
//pc_body_2 /404 Begins Here

//pc_body_2 /404 Ends Here
?>


<!-- /.row --><!-- Content Row -->
<?php
//pc_body_3 Begins Here

//pc_body_3 Ends Here
?><?php
//pc_body_3 /404 Begins Here

//pc_body_3 /404 Ends Here
?>



        <!-- /.row -->

        <!-- Footer -->
        
<?php
//pc_body_4 Begins Here

//pc_body_4 Ends Here
?><?php
//pc_body_4 /404 Begins Here

//pc_body_4 /404 Ends Here
?>



</div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/bootstrapbasic/js/jquery.js"></script><!-- Bootstrap Core JavaScript --><script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/bootstrapbasic/js/bootstrap.min.js"></script><?php include_once( LAYOUT_PATH . DS . 'footerJs' . TPL ) ?><?php include_once( LAYOUT_PATH . DS . 'footer' . TPL ) ?>
<?php
//pc_section_after_js Begins Here

//pc_section_after_js Ends Here
?><?php
//pc_section_after_js /404 Begins Here

//pc_section_after_js /404 Ends Here
?>

</body>
</html>
