<?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /account
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: account.php	Wednesday 10th of April 2019 02:16:48 PM	ayoola@ayoo.la $ 
*/
//	Template Content ?>

						<?php 
						//		var_export( array_pop( explode( PC_BASE, Ayoola_Application::getDomainSettings( APPLICATION_PATH ) ) ) );
					//			var_export( __FILE__ );
					//			var_export( CACHE_DIR );
					//			var_export( stripos( __FILE__, Ayoola_Application::getDomainSettings( APPLICATION_DIR ) ) );
								//	ADDED TO CHECK WITH CACHE_DIR TOO BECAUSE OF EDITING THEME PAGES
								//	THEY WON'T HAVE CORRECT APPDIR
//								var_export( stripos( __FILE__,CACHE_DIR ) );
			//					var_export( Ayoola_Application::getDomainSettings( APPLICATION_DIR ) );
			//					var_export( Ayoola_Application::getDomainSettings() );
							if
							( 

								$x_1554905808 = Ayoola_Filter_LayoutIdToPath::getThemeIncludeFile( 'bootstrapbasic', stripos( __FILE__, Ayoola_Application::getDomainSettings( APPLICATION_DIR ) ) !== false || stripos( __FILE__,CACHE_DIR ) !== false ? array( 'prioritize_my_copy' => true, 'multiple' => true,  ) : array( 'path_blacklist' => array_pop( explode( PC_BASE, Ayoola_Application::getDomainSettings( APPLICATION_PATH ) ) ), 'multiple' => true ) ) 
							)
							{
							//	var_export( $x_1554905808 );
							//	echo file_get_contents( $x_1554905808 );
								foreach( $x_1554905808 as $each )
								{	
									include_once $each;
								}
							}
		//					var_export( $x_1554905808 );
						?>
						 <?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /layout/bootstrapbasic/template
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: template.php	Thursday 19th of April 2018 11:14:54 AM	ayoola@ayoo.la $ 
*/
//	Template Content ?>
<!DOCTYPE html>
<html lang="en">
<head>
<?php include_once( LAYOUT_PATH . DS . 'htmlHeader' . TPL ) ?>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="author" content="">
<!-- Bootstrap Core CSS --><link href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/bootstrapbasic/css/bootstrap.min.css" rel="stylesheet">
<!-- Custom CSS --><link href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/bootstrapbasic/css/small-business.css" rel="stylesheet">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries --><!-- WARNING: Respond.js doesn't work if you view the page via file:// --><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]--><link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>
<body style="background-color: #ddd;" data-pc-section-name="body">

    <!-- Navigation -->
<nav id="mainnav" class="navbar navbar-inverse navbar-fixed-top" role="navigation" data-pc-menu-id-list=",bs-example-navbar-collapse-1" data-pc-menu-ul-class-bs-example-navbar-collapse-1="nav navbar-nav navbar-right" data-pc-menu-li-active-class-bs-example-navbar-collapse-1="dropdown" data-pc-menu-li-ul-class-bs-example-navbar-collapse-1="dropdown-menu"><div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar">&nbsp;</span>
                    <span class="icon-bar">&nbsp;</span>
                    <span class="icon-bar">&nbsp;</span>
                </button>
                <a class="navbar-brand" style="height:auto;height:initial;height:unset;" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/"><img style="max-height:50px;" name="pc-logo" src="<?php echo Ayoola_Doc::getLogo(); ?>"></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <?php echo Ayoola_Menu_Demo::viewInLine( array( 'option' => 'mainnav', 'li-active-class' => 'dropdown', 'ul-class' => 'nav navbar-nav navbar-right', 'ul-id' => '', )  ); ?>
</div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav><!-- Page Content --><div class="container" data-pc-section-autonamed="1" data-pc-section-name="pc-body-1">

        <!-- Heading Row -->
		<section data-pc-all-sections="1">	
									<?php
//oneness Begins Here

echo ( ! empty( $_b7050bae07234eabc14cec6521a7fe97 ) &&  is_object( $_b7050bae07234eabc14cec6521a7fe97 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_b7050bae07234eabc14cec6521a7fe97->view(), '' ) : null );

//oneness Ends Here
?><?php
//oneness Begins Here

//oneness Ends Here
?>
									<div class="">
										<div class="row">
											<div class="col-md-12 12u">
												<?php
//middlebar Begins Here

//middlebar Ends Here
?><?php
//middlebar Begins Here

echo ( ! empty( $_2f63bc0963e9afc89bc511de893c11fc ) &&  is_object( $_2f63bc0963e9afc89bc511de893c11fc ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_2f63bc0963e9afc89bc511de893c11fc->view(), '' ) : null );

//middlebar Ends Here
?>
										   </div>
										</div> 
										<div class="row">
											<div class="col-sm-6 6u 6u(medium) 12u$(xsmall)">
												<?php
//twosome1 Begins Here

//twosome1 Ends Here
?><?php
//twosome1 Begins Here

echo ( ! empty( $_692509e191fac1d67c625e321c4395b7 ) &&  is_object( $_692509e191fac1d67c625e321c4395b7 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_692509e191fac1d67c625e321c4395b7->view(), 'dark' ) : null );

echo ( ! empty( $_356f72d00671943948b1fee15fdc71ec ) &&  is_object( $_356f72d00671943948b1fee15fdc71ec ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_356f72d00671943948b1fee15fdc71ec->view(), '' ) : null );

//twosome1 Ends Here
?>
											</div>
											<div class="col-sm-6 6u 6u(medium) 12u$(xsmall)">
												<?php
//twosome2 Begins Here

//twosome2 Ends Here
?><?php
//twosome2 Begins Here

echo ( ! empty( $_812a3c03c828e0fad72b06706dd89e2c ) &&  is_object( $_812a3c03c828e0fad72b06706dd89e2c ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_812a3c03c828e0fad72b06706dd89e2c->view(), 'dark' ) : null );

echo ( ! empty( $_edca16dd549bfe09f69705d257712133 ) &&  is_object( $_edca16dd549bfe09f69705d257712133 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_edca16dd549bfe09f69705d257712133->view(), 'well' ) : null );

//twosome2 Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="col-md-4 4u 12u$(medium) 12u$(xsmall)"> 
												<?php
//threesome1 Begins Here

//threesome1 Ends Here
?><?php
//threesome1 Begins Here

//threesome1 Ends Here
?>
										   </div>
											<div class="col-md-4 4u 12u$(medium) 12u$(xsmall)">
												<?php
//threesome2 Begins Here

//threesome2 Ends Here
?><?php
//threesome2 Begins Here

//threesome2 Ends Here
?>
											</div> 
											<div class="col-md-4 4u 12u$(medium) 12u$(xsmall)">
												<?php
//threesome3 Begins Here

//threesome3 Ends Here
?><?php
//threesome3 Begins Here

//threesome3 Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="col-md-3 3u 6u(medium) 12u$(xsmall)">
												<?php
//foursome1 Begins Here

//foursome1 Ends Here
?><?php
//foursome1 Begins Here

//foursome1 Ends Here
?>
										   </div>
											<div class="col-md-3 3u 6u$(medium) 12u$(xsmall)">
												<?php
//foursome2 Begins Here

//foursome2 Ends Here
?><?php
//foursome2 Begins Here

//foursome2 Ends Here
?>
											</div> 
											<div class="col-md-3 3u 6u(medium) 12u$(xsmall)">
												<?php
//foursome3 Begins Here

//foursome3 Ends Here
?><?php
//foursome3 Begins Here

//foursome3 Ends Here
?>
											</div> 
											<div class="col-md-3 3u 6u$(medium) 12u$(xsmall)">    
												<?php
//foursome4 Begins Here

//foursome4 Ends Here
?><?php
//foursome4 Begins Here

//foursome4 Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="col-md-4 4u 12u$(medium) 12u$(xsmall)">
												<?php
//leftbar Begins Here

//leftbar Ends Here
?><?php
//leftbar Begins Here

//leftbar Ends Here
?>
										   </div>
											<div class="col-md-8 8u 12u$(medium) 12u$(xsmall)">
												<?php
//leftbarright Begins Here

//leftbarright Ends Here
?><?php
//leftbarright Begins Here

//leftbarright Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="col-md-8 8u 12u$(medium) 12u$(xsmall)">
												<?php
//rightbarleft Begins Here

//rightbarleft Ends Here
?><?php
//rightbarleft Begins Here

//rightbarleft Ends Here
?>
											</div> 
											<div class="col-md-4 4u 12u$(medium) 12u$(xsmall)">
												<?php
//rightbar Begins Here

//rightbar Ends Here
?><?php
//rightbar Begins Here

//rightbar Ends Here
?>
											</div>   
										</div> 
									</div> 
									<?php
//lastoneness Begins Here

//lastoneness Ends Here
?><?php
//lastoneness Begins Here

							if( Ayoola_Page::hasPriviledge( array (
  0 => '98',
  1 => '99',
), array( 'strict' => true ) ) && ! empty( $_d687a55ad8784085b5b9dd53060bad5c ) && is_object( $_d687a55ad8784085b5b9dd53060bad5c ) )
							{
								echo $_d687a55ad8784085b5b9dd53060bad5c->view();
							}
							
echo ( ! empty( $_a7e752f58e7a7c50ee706917a2a53a70 ) &&  is_object( $_a7e752f58e7a7c50ee706917a2a53a70 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_a7e752f58e7a7c50ee706917a2a53a70->view(), '' ) : null );

//lastoneness Ends Here
?>
								</section><div class="row" data-pc-section-autonamed="1" data-pc-section-name="pc-body-1">
		
<?php
//headline Begins Here

//headline Ends Here
?><?php
//headline Begins Here

//headline Ends Here
?>



</div>
        <!-- /.row -->

        <hr>
<!-- Call to Action Well -->
<?php
//actionwell Begins Here

//actionwell Ends Here
?><?php
//actionwell Begins Here

//actionwell Ends Here
?>


<!-- /.row --><!-- Content Row --><div class="row" data-pc-section-autonamed="3" data-pc-section-name="pc-body-3">
 		
<?php
//content Begins Here

//content Ends Here
?><?php
//content Begins Here

//content Ends Here
?>



</div>
        <!-- /.row -->

        <!-- Footer -->
        
<?php
//footer Begins Here

echo ( ! empty( $_b71609262e8e97539bd6fa137dd38be4 ) &&  is_object( $_b71609262e8e97539bd6fa137dd38be4 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_b71609262e8e97539bd6fa137dd38be4->view(), '' ) : null );

							if( Ayoola_Page::hasPriviledge( array (
  0 => '98',
  1 => '99',
), array( 'strict' => true ) ) && ! empty( $_199d60ed2c8487d949bc81e7e1cdd92e ) && is_object( $_199d60ed2c8487d949bc81e7e1cdd92e ) )
							{
								echo $_199d60ed2c8487d949bc81e7e1cdd92e->view();
							}
							
//footer Ends Here
?><?php
//footer Begins Here

//footer Ends Here
?>



</div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/bootstrapbasic/js/jquery.js"></script><!-- Bootstrap Core JavaScript --><script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/bootstrapbasic/js/bootstrap.min.js"></script><?php include_once( LAYOUT_PATH . DS . 'footerJs' . TPL ) ?>
</body>
</html>
