<?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /pc-admin
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: pc-admin.php	Saturday 14th of December 2019 04:58:47 PM	ayoola@ayoo.la $ 
*/
//	Template Content ?>

						<?php 
						//		var_export( array_pop( explode( PC_BASE, Ayoola_Application::getDomainSettings( APPLICATION_PATH ) ) ) );
					//			var_export( __FILE__ );
					//			var_export( CACHE_DIR );
					//			var_export( stripos( __FILE__, Ayoola_Application::getDomainSettings( APPLICATION_DIR ) ) );
								//	ADDED TO CHECK WITH CACHE_DIR TOO BECAUSE OF EDITING THEME PAGES
								//	THEY WON'T HAVE CORRECT APPDIR
//								var_export( stripos( __FILE__,CACHE_DIR ) );
			//					var_export( Ayoola_Application::getDomainSettings( APPLICATION_DIR ) );
			//					var_export( Ayoola_Application::getDomainSettings() );
							if
							( 

								$x_1576342727 = Ayoola_Filter_LayoutIdToPath::getThemeIncludeFile( 'novus', stripos( __FILE__, Ayoola_Application::getDomainSettings( APPLICATION_DIR ) ) !== false || stripos( __FILE__,CACHE_DIR ) !== false ? array( 'prioritize_my_copy' => true, 'multiple' => true,  ) : array( 'path_blacklist' => @array_pop( explode( PC_BASE, Ayoola_Application::getDomainSettings( APPLICATION_PATH ) ) ), 'multiple' => true ) ) 
							)
							{
							//	var_export( $x_1576342727 );
							//	echo file_get_contents( $x_1576342727 );
								foreach( $x_1576342727 as $each )
								{	
									include_once $each;
								}
							}
		//					var_export( $x_1576342727 );
						?>
						 <?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /layout/novus/template
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: template.php	Monday 2nd of December 2019 11:38:46 AM	ayoola@ayoo.la $ 
*/
//	Template Content ?>
<!DOCTYPE HTML>
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
--><html>
<head>
<?php include_once( LAYOUT_PATH . DS . 'htmlHeader' . TPL ) ?>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script><!-- Bootstrap Core CSS --><link href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/css/bootstrap.css" rel="stylesheet" type="text/css">
<!-- Custom CSS --><link href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/css/style.css" rel="stylesheet" type="text/css">
<!-- font CSS --><!-- font-awesome icons --><link href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/css/font-awesome.css" rel="stylesheet">
<!-- //font-awesome icons --><!-- js--><script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/jquery-1.11.1.min.js"></script><script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/modernizr.custom.js"></script><!--webfonts--><link href="//fonts.googleapis.com/css?family=Roboto+Condensed:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css">
<!--//webfonts--><!--animate--><link href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/css/animate.css" rel="stylesheet" type="text/css" media="all">
<script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/wow.min.js"></script><script>
		new WOW().init();
	</script><!--//end-animate--><!-- chart --><script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/Chart.js"></script><!-- //chart --><!--Calender--><link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/css/clndr.css" type="text/css">
<script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/underscore-min.js" type="text/javascript"></script><script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/moment-2.2.1.js" type="text/javascript"></script><!--<script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/clndr.js" type="text/javascript"></script>  
<script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/site.js" type="text/javascript"></script>--><!--End Calender--><!-- Metis Menu --><script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/metisMenu.min.js"></script><script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/custom.js"></script><link href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/css/custom.css" rel="stylesheet">
<!--//Metis Menu --><style>
		.row {
			margin: 0 0 0;
		}

		.logo a h1 {
			color: transparent;
			background-image: url(<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/"<?php echo Ayoola_Application::getUrlPrefix(); ?>/img/logo.png);
			background-position: center;
			background-size: contain;
			background-repeat: no-repeat;
		}

		.logo {
			background: #4d4d4d;
			float: unset;
		}

		.cbp-spmenu-vertical {
			background-color: #333;
		}

		.header-left {
			float: unset;
			width: unset;
		}
		@media(max-width:640px) {
			.cbp-spmenu-push div#page-wrapper {

				padding: 5em 1em 2em;

			}
		}
	</style>
</head>
<body class="cbp-spmenu-push" data-pc-section-name="body">
<?php include_once( LAYOUT_PATH . DS . 'header' . TPL ) ?>
	<div class="main-content" data-pc-section-autonamed="1" data-pc-section-name="pc-body-1">
		<!--left-fixed -navigation-->
		<div class=" sidebar" role="navigation" data-pc-section-autonamed="1" data-pc-section-name="pc-body-1">
			<div class="navbar-collapse">
				<nav data-pc-menu-ignore="1" class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1"><!-- //sidebar-collapse -->
<?php
//nav_one Begins Here

                foreach( $_sitePageWidget_nav_one as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
echo ( ! empty( $_acd6c67e7aeba849612416a4d14168e1 ) &&  is_object( $_acd6c67e7aeba849612416a4d14168e1 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_acd6c67e7aeba849612416a4d14168e1->view(), '' ) : null );

//nav_one Ends Here
?><?php
//nav_one Begins Here

//nav_one Ends Here
?>


</nav>
</div>
		</div>
		<!--left-fixed -navigation-->
		<!-- header-starts -->
		<div class="sticky-header header-section " data-pc-section-autonamed="2" data-pc-section-name="pc-body-2">
			<div class="header-left">
				<!--toggle button start-->
				<button id="showLeftPush"><i class="fa fa-bars">&nbsp;</i></button>
				<!--toggle button end-->
				<!--logo -->
				<div class="logo">
					<a href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/pc-admin">
						<h1>PageCarton</h1>
						<span>PageCarton Admin Panel</span>
					</a>
				</div>
				<!--//logo-->
				<!--search-box-
				<div class="search-box">
					<form action="<?php echo Ayoola_Application::getUrlPrefix(); ?>/search/" class="input">
						<input class="sb-search-input input__field--madoka" placeholder="Search..." type="search" id="input-31" />
						<label class="input__label" for="input-31">
							<svg class="graphic" width="100%" height="100%" viewBox="0 0 404 77" preserveAspectRatio="none">
								<path d="m0,0l404,0l0,77l-404,0l0,-77z"/>   
							</svg>
						</label>
					</form>
				</div><!--//end-search-box-->
				<div class="clearfix"> </div>
			</div>
			<div class="header-right">

				<!--notification menu end -->
			</div>
			<div class="clearfix"> </div>
		</div>
		<!-- //header-ends -->
		<!-- main content start-->
		<div id="page-wrapper" data-pc-section-autonamed="3" data-pc-section-name="pc-body-3">
			<div class="main-page">
				<section><?php
//oneness Begins Here

                foreach( $_sitePageWidget_oneness as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
echo ( ! empty( $_7dd175ad4ab7614d4cc6b13e510bd274 ) &&  is_object( $_7dd175ad4ab7614d4cc6b13e510bd274 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_7dd175ad4ab7614d4cc6b13e510bd274->view(), '' ) : null );

//oneness Ends Here
?><?php
//oneness Begins Here

echo ( ! empty( $_0c31198ab8134b66fc7a6a729689ad1e ) &&  is_object( $_0c31198ab8134b66fc7a6a729689ad1e ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_0c31198ab8134b66fc7a6a729689ad1e->view(), '' ) : null );

echo ( ! empty( $_26a4384ebf0e9ca07bbc60f3df847c8b ) &&  is_object( $_26a4384ebf0e9ca07bbc60f3df847c8b ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_26a4384ebf0e9ca07bbc60f3df847c8b->view(), '' ) : null );

echo ( ! empty( $_a5aa57c39772cebde1fff97f73dc5103 ) &&  is_object( $_a5aa57c39772cebde1fff97f73dc5103 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_a5aa57c39772cebde1fff97f73dc5103->view(), '' ) : null );

							if( Ayoola_Page::hasPriviledge( array (
  0 => '99',
), array( 'strict' => true ) ) && ! empty( $_7e3ed0a5d2f967efa56477075a9f3bec ) && is_object( $_7e3ed0a5d2f967efa56477075a9f3bec ) )
							{
								echo $_7e3ed0a5d2f967efa56477075a9f3bec->view();
							}
							
echo ( ! empty( $_5795f2af0334c6567383585ed4bda459 ) &&  is_object( $_5795f2af0334c6567383585ed4bda459 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_5795f2af0334c6567383585ed4bda459->view(), 'white-well' ) : null );

echo ( ! empty( $_5d8b8384509636edca9a1682938343eb ) &&  is_object( $_5d8b8384509636edca9a1682938343eb ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_5d8b8384509636edca9a1682938343eb->view(), '' ) : null );

echo ( ! empty( $_0cdc55584796284b6ab2ffa1f70e3c89 ) &&  is_object( $_0cdc55584796284b6ab2ffa1f70e3c89 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_0cdc55584796284b6ab2ffa1f70e3c89->view(), 'white-well' ) : null );

echo ( ! empty( $_097c066c3ed3dbb233d013989a9586b7 ) &&  is_object( $_097c066c3ed3dbb233d013989a9586b7 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_097c066c3ed3dbb233d013989a9586b7->view(), '' ) : null );

//oneness Ends Here
?><section data-pc-all-sections="1">	
									<div class="">
										<div class="row">
											<div class="pc_page_layout_grid col-md-12 12u">
												<?php
//middlebar Begins Here

                foreach( $_sitePageWidget_middlebar as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//middlebar Ends Here
?><?php
//middlebar Begins Here

//middlebar Ends Here
?>
										   </div>
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-6 6u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//twosome1 Begins Here

                foreach( $_sitePageWidget_twosome1 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//twosome1 Ends Here
?><?php
//twosome1 Begins Here

//twosome1 Ends Here
?>
											</div>
											<div class="pc_page_layout_grid col-sm-6 6u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//twosome2 Begins Here

                foreach( $_sitePageWidget_twosome2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//twosome2 Ends Here
?><?php
//twosome2 Begins Here

//twosome2 Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)"> 
												<?php
//threesome1 Begins Here

                foreach( $_sitePageWidget_threesome1 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//threesome1 Ends Here
?><?php
//threesome1 Begins Here

//threesome1 Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//threesome2 Begins Here

                foreach( $_sitePageWidget_threesome2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//threesome2 Ends Here
?><?php
//threesome2 Begins Here

//threesome2 Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//threesome3 Begins Here

                foreach( $_sitePageWidget_threesome3 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//threesome3 Ends Here
?><?php
//threesome3 Begins Here

//threesome3 Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome1 Begins Here

                foreach( $_sitePageWidget_foursome1 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome1 Ends Here
?><?php
//foursome1 Begins Here

//foursome1 Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome2 Begins Here

                foreach( $_sitePageWidget_foursome2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome2 Ends Here
?><?php
//foursome2 Begins Here

//foursome2 Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-3 3u 6u(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome3 Begins Here

                foreach( $_sitePageWidget_foursome3 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome3 Ends Here
?><?php
//foursome3 Begins Here

//foursome3 Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">    
												<?php
//foursome4 Begins Here

                foreach( $_sitePageWidget_foursome4 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome4 Ends Here
?><?php
//foursome4 Begins Here

//foursome4 Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//leftbar Begins Here

                foreach( $_sitePageWidget_leftbar as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//leftbar Ends Here
?><?php
//leftbar Begins Here

//leftbar Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-8 8u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//leftbarright Begins Here

                foreach( $_sitePageWidget_leftbarright as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//leftbarright Ends Here
?><?php
//leftbarright Begins Here

//leftbarright Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-8 8u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//rightbarleft Begins Here

                foreach( $_sitePageWidget_rightbarleft as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//rightbarleft Ends Here
?><?php
//rightbarleft Begins Here

//rightbarleft Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//rightbar Begins Here

                foreach( $_sitePageWidget_rightbar as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//rightbar Ends Here
?><?php
//rightbar Begins Here

//rightbar Ends Here
?>
											</div>   
										</div> 
									</div> 
								</section><?php
//lastoneness Begins Here

                foreach( $_sitePageWidget_lastoneness as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//lastoneness Ends Here
?><?php
//lastoneness Begins Here

//lastoneness Ends Here
?></section>
<?php
//row_one Begins Here

                foreach( $_sitePageWidget_row_one as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//row_one Ends Here
?><?php
//row_one Begins Here

//row_one Ends Here
?>



<?php
//charts Begins Here

                foreach( $_sitePageWidget_charts as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//charts Ends Here
?><?php
//charts Begins Here

//charts Ends Here
?>



<?php
//three Begins Here

                foreach( $_sitePageWidget_three as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//three Ends Here
?><?php
//three Begins Here

//three Ends Here
?>



<?php
//four Begins Here

                foreach( $_sitePageWidget_four as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//four Ends Here
?><?php
//four Begins Here

//four Ends Here
?>



<?php
//five Begins Here

                foreach( $_sitePageWidget_five as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//five Ends Here
?><?php
//five Begins Here

//five Ends Here
?>


<div class="clearfix"> </div>
			</div>
		</div>
		<!--footer-->
		<div class="main-page" data-pc-section-autonamed="4" data-pc-section-name="pc-body-4">
			<div class="footer">
				
<?php
//footer Begins Here

                foreach( $_sitePageWidget_footer as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//footer Ends Here
?><?php
//footer Begins Here

echo ( ! empty( $_eeb3b955e392533b3850e947803473e8 ) &&  is_object( $_eeb3b955e392533b3850e947803473e8 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_eeb3b955e392533b3850e947803473e8->view(), '' ) : null );

//footer Ends Here
?>



</div>
		</div>
		<!--//footer-->
	</div>
	<!-- Classie -->
	<script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/classie.js"></script><script>
		var menuLeft = document.getElementById('cbp-spmenu-s1'),
			showLeftPush = document.getElementById('showLeftPush'),
			body = document.body;

		showLeftPush.onclick = function () {
			classie.toggle(this, 'active');
			classie.toggle(body, 'cbp-spmenu-push-toright');
			classie.toggle(menuLeft, 'cbp-spmenu-open');
			disableOther('showLeftPush');
		};


		function disableOther(button) {
			if (button !== 'showLeftPush') {
				classie.toggle(showLeftPush, 'disabled');
			}
		}
	</script><!--scrolling js--><script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/jquery.nicescroll.js"></script><script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/scripts.js"></script><!--//scrolling js--><!-- Bootstrap Core JavaScript --><script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/bootstrap.js"> </script><?php include_once( LAYOUT_PATH . DS . 'footerJs' . TPL ) ?><?php include_once( LAYOUT_PATH . DS . 'footer' . TPL ) ?>
</body>
</html>
