<?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /pc-admin
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: pc-admin.php	Wednesday 26th of December 2018 12:27:31 AM	ayoola@ayoo.la $ 
*/
//	Template Content ?>

						<?php 
						//		var_export( array_pop( explode( PC_BASE, Ayoola_Application::getDomainSettings( APPLICATION_PATH ) ) ) );
					//			var_export( __FILE__ );
					//			var_export( CACHE_DIR );
					//			var_export( stripos( __FILE__, Ayoola_Application::getDomainSettings( APPLICATION_DIR ) ) );
								//	ADDED TO CHECK WITH CACHE_DIR TOO BECAUSE OF EDITING THEME PAGES
								//	THEY WON'T HAVE CORRECT APPDIR
//								var_export( stripos( __FILE__,CACHE_DIR ) );
			//					var_export( Ayoola_Application::getDomainSettings( APPLICATION_DIR ) );
			//					var_export( Ayoola_Application::getDomainSettings() );
							if
							( 

								$x_1545784052 = Ayoola_Filter_LayoutIdToPath::getThemeIncludeFile( 'novus', stripos( __FILE__, Ayoola_Application::getDomainSettings( APPLICATION_DIR ) ) !== false || stripos( __FILE__,CACHE_DIR ) !== false ? array( 'prioritize_my_copy' => true, 'multiple' => true,  ) : array( 'path_blacklist' => array_pop( explode( PC_BASE, Ayoola_Application::getDomainSettings( APPLICATION_PATH ) ) ), 'multiple' => true ) ) 
							)
							{
							//	var_export( $x_1545784052 );
							//	echo file_get_contents( $x_1545784052 );
								foreach( $x_1545784052 as $each )
								{	
									include_once $each;
								}
							}
		//					var_export( $x_1545784052 );
						?>
						 <?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /layout/novus/template
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: template.php	Tuesday 25th of December 2018 11:56:25 PM	ayoola@ayoo.la $ 
*/
//	Template Content ?>
<!DOCTYPE HTML>
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
--><html>
<head>
<?php include_once( LAYOUT_PATH . DS . 'htmlHeader' . TPL ) ?>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script><!-- Bootstrap Core CSS --><link href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/css/bootstrap.css" rel="stylesheet" type="text/css">
<!-- Custom CSS --><link href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/css/style.css" rel="stylesheet" type="text/css">
<!-- font CSS --><!-- font-awesome icons --><link href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/css/font-awesome.css" rel="stylesheet">
<!-- //font-awesome icons --><!-- js--><script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/jquery-1.11.1.min.js"></script><script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/modernizr.custom.js"></script><!--webfonts--><link href="//fonts.googleapis.com/css?family=Roboto+Condensed:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css">
<!--//webfonts--><!--animate--><link href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/css/animate.css" rel="stylesheet" type="text/css" media="all">
<script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/wow.min.js"></script><script>
		 new WOW().init();
	</script><!--//end-animate--><!-- chart --><script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/Chart.js"></script><!-- //chart --><!--Calender--><link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/css/clndr.css" type="text/css">
<script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/underscore-min.js" type="text/javascript"></script><script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/moment-2.2.1.js" type="text/javascript"></script><!--<script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/clndr.js" type="text/javascript"></script>  
<script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/site.js" type="text/javascript"></script>--><!--End Calender--><!-- Metis Menu --><script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/metisMenu.min.js"></script><script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/custom.js"></script><link href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/css/custom.css" rel="stylesheet">
<!--//Metis Menu --><style>
	.row {
    margin: 0 0 0;
}
.logo a h1 {
    color: transparent;
    background-image: url("<?php echo Ayoola_Application::getUrlPrefix(); ?>/img/logo.png");
    background-position: center;
    background-size: contain;
    background-repeat: no-repeat;
}
		.logo {
			background: #4d4d4d;
			float: unset;
		}

		.cbp-spmenu-vertical {
			background-color: #333;
		}

		.header-left {
			float: unset;
			width: unset;
		}
@media(max-width:640px){
.cbp-spmenu-push div#page-wrapper {

    padding: 5em 1em 2em;

}
}
</style>
</head>
<body class="cbp-spmenu-push" data-pc-section-name="body">
<?php include_once( LAYOUT_PATH . DS . 'header' . TPL ) ?>
	<div class="main-content" data-pc-section-autonamed="1" data-pc-section-name="pc-body-1">
		<!--left-fixed -navigation-->
		<div class=" sidebar" role="navigation" data-pc-section-autonamed="1" data-pc-section-name="pc-body-1">
            <div class="navbar-collapse"> 
				<nav data-pc-menu-ignore="1" class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1"><ul class="nav" id="side-menu">
<li>   
							<a href="#"><i class="fa fa-cogs nav_icon">&nbsp;</i>Settings <span class="fa arrow">&nbsp;</span></a>
							<ul class="nav nav-second-level collapse">
<li>
									<a href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/pc-admin/name/Application_Settings_SettingsName_List/">Options</a>
								</li>
								<li>
									<a href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/pc-admin/name/Ayoola_Access_AuthLevel_List/">Privileges</a>
								</li>
								<li>
									<a href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/pc-admin/name/Ayoola_Object_List/">Widgets</a>
								</li>
								<li>
									<a href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/pc-admin/name/PageCarton_MultiSite_List/">Multi-site Manager</a>
								</li>
								<li>
									<a href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/pc-admin/name/Application_Backup_List/">Back up &amp; Restore</a>
								</li>
								<li>
									<a href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/pc-admin/name/Application_Log/">Logs</a>
								</li>
								<li>
									<a href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/pc-admin/name/Application_Cache_Clear/">Clear Cache</a>
								</li>
								<li>
									<a href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/pc-admin/name/Application_Upgrade/">Upgrades</a>
								</li>
							</ul>
<!-- /nav-second-level -->
</li>
						<li>
							<a href="#"><i class="fa fa-file-text-o nav_icon">&nbsp;</i>Appearance <span class="fa arrow">&nbsp;</span></a>
							<ul class="nav nav-second-level collapse">
<li>
									<a href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/pc-admin/name/Ayoola_Page_List/">Pages</a>
								</li>
								<li>
									<a href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/pc-admin/name/Ayoola_Page_Layout_List/">Themes</a>
								</li>
								<li>
									<a href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/pc-admin/name/Ayoola_Page_Menu_List/">Navigation</a>
								</li>
								<li>
									<a onclick="ayoola.spotLight.showLinkInIFrame( '<?php echo Ayoola_Application::getUrlPrefix(); ?>/tools/classplayer/get/object_name/Ayoola_Doc_Upload_Link/?image_url=/img/logo.png' );" href="javascript:">Logo</a>
								</li>
								<li>
									<a onclick="ayoola.spotLight.showLinkInIFrame( '<?php echo Ayoola_Application::getUrlPrefix(); ?>/tools/classplayer/get/object_name/Ayoola_Doc_Upload_Link/?image_url=/favicon.ico' );" href="javascript:">Favicon</a>
								</li>
							</ul>
<!-- //nav-second-level -->
</li>
						<li class="">
							<a href="#"><i class="fa fa-users nav_icon">&nbsp;</i>Users   <span class="fa arrow">&nbsp;</span></a>
							<ul class="nav nav-second-level collapse">
<li>
									<a href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/pc-admin/name/Application_User_List/">User Accounts</a>
								</li>
								<li>
									<a href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/pc-admin/name/Application_XmlTableViewer/table_name/Application_User_UserEmail_MailingList/">Mailing List</a>
								</li>
								<li>
									<a href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/pc-admin/name/Application_User_NotificationMessage_List/">Bulk Mails</a>
								</li>
							</ul>
<!-- /nav-second-level -->
</li>
						<li>
							<a href="#"><i class="fa fa-circle nav_icon">&nbsp;</i>Plugins <span class="fa arrow">&nbsp;</span></a>
							<ul class="nav nav-second-level collapse">
<li>
									<a href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/pc-admin/name/Ayoola_Extension_Import_List/">Installed Plugins</a>
								</li>
								<li>
									<a href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/pc-admin/name/Ayoola_Extension_List/">My Plugins</a>
								</li>
							</ul>
<!-- /nav-second-level -->
</li>
						<li>
							<a href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/pc-admin/name/Ayoola_Form_List/"><i class="fa fa-check-square-o nav_icon">&nbsp;</i>Forms </a>
						</li>
						<li>
							<a href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/pc-admin/name/Application_Article_List/"><i class="fa fa-th-large nav_icon">&nbsp;</i>Posts </a>
						</li>						
						
					</ul>
<!-- //sidebar-collapse --></nav>
</div>
		</div>
		<!--left-fixed -navigation-->
		<!-- header-starts -->
		<div class="sticky-header header-section " data-pc-section-autonamed="2" data-pc-section-name="pc-body-2">
			<div class="header-left">
				<!--toggle button start-->
				<button id="showLeftPush"><i class="fa fa-bars">&nbsp;</i></button>
				<!--toggle button end-->
				<!--logo -->
				<div class="logo">
					<a href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/pc-admin">
						<h1>PageCarton</h1>
						<span>PageCarton Admin Panel</span>
					</a>				
				</div>
				<!--//logo-->
				<!--search-box-
				<div class="search-box">
					<form action="<?php echo Ayoola_Application::getUrlPrefix(); ?>/search/" class="input">
						<input class="sb-search-input input__field--madoka" placeholder="Search..." type="search" id="input-31" />
						<label class="input__label" for="input-31">
							<svg class="graphic" width="100%" height="100%" viewBox="0 0 404 77" preserveAspectRatio="none">
								<path d="m0,0l404,0l0,77l-404,0l0,-77z"/>    
							</svg>
						</label>
					</form>
				</div><!--//end-search-box-->
				<div class="clearfix"> </div>
			</div>
			<div class="clearfix"> </div>	
		</div>
		<!-- //header-ends -->
		<!-- main content start-->
		<div id="page-wrapper" data-pc-section-name="page-wrapper">
			<div class="main-page">
				<section><?php
//oneness Begins Here

echo ( ! empty( $_dac83995f15adeba352e9940462f4228 ) &&  is_object( $_dac83995f15adeba352e9940462f4228 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_dac83995f15adeba352e9940462f4228->view(), '' ) : null );

//oneness Ends Here
?><?php
//oneness Begins Here

echo ( ! empty( $_0b9ac26e3cbcd36692cd5b2ccadf626e ) &&  is_object( $_0b9ac26e3cbcd36692cd5b2ccadf626e ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_0b9ac26e3cbcd36692cd5b2ccadf626e->view(), 'well' ) : null );

echo ( ! empty( $_28742e28f5492c7b1e886e903e64c3c3 ) &&  is_object( $_28742e28f5492c7b1e886e903e64c3c3 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_28742e28f5492c7b1e886e903e64c3c3->view(), '' ) : null );

							if( Ayoola_Page::hasPriviledge( array (
  0 => '99',
), array( 'strict' => true ) ) && ! empty( $_fdb452d3ce6343c66d26aed2671ec2d9 ) && is_object( $_fdb452d3ce6343c66d26aed2671ec2d9 ) )
							{
								echo $_fdb452d3ce6343c66d26aed2671ec2d9->view();
							}
							
echo ( ! empty( $_76e7e3da660c3d8115385434d8c36c76 ) &&  is_object( $_76e7e3da660c3d8115385434d8c36c76 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_76e7e3da660c3d8115385434d8c36c76->view(), 'white-well' ) : null );

echo ( ! empty( $_848972eb36aa04b62e7b6ec01bae0040 ) &&  is_object( $_848972eb36aa04b62e7b6ec01bae0040 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_848972eb36aa04b62e7b6ec01bae0040->view(), '' ) : null );

echo ( ! empty( $_d9e5cb31e5f2858952223a83bcfbe5b8 ) &&  is_object( $_d9e5cb31e5f2858952223a83bcfbe5b8 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_d9e5cb31e5f2858952223a83bcfbe5b8->view(), 'white-well' ) : null );

echo ( ! empty( $_81887aceed5b28012e715c3090815557 ) &&  is_object( $_81887aceed5b28012e715c3090815557 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_81887aceed5b28012e715c3090815557->view(), '' ) : null );

//oneness Ends Here
?><section data-pc-all-sections="1">	
									<div class="">
										<div class="row">
											<div class="pc_page_layout_grid col-md-12 12u">
												<?php
//middlebar Begins Here

//middlebar Ends Here
?><?php
//middlebar Begins Here

//middlebar Ends Here
?>
										   </div>
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-6 6u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//twosome1 Begins Here

//twosome1 Ends Here
?><?php
//twosome1 Begins Here

//twosome1 Ends Here
?>
											</div>
											<div class="pc_page_layout_grid col-sm-6 6u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//twosome2 Begins Here

//twosome2 Ends Here
?><?php
//twosome2 Begins Here

//twosome2 Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)"> 
												<?php
//threesome1 Begins Here

//threesome1 Ends Here
?><?php
//threesome1 Begins Here

//threesome1 Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//threesome2 Begins Here

//threesome2 Ends Here
?><?php
//threesome2 Begins Here

//threesome2 Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//threesome3 Begins Here

//threesome3 Ends Here
?><?php
//threesome3 Begins Here

//threesome3 Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome1 Begins Here

//foursome1 Ends Here
?><?php
//foursome1 Begins Here

//foursome1 Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome2 Begins Here

//foursome2 Ends Here
?><?php
//foursome2 Begins Here

//foursome2 Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-3 3u 6u(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome3 Begins Here

//foursome3 Ends Here
?><?php
//foursome3 Begins Here

//foursome3 Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">    
												<?php
//foursome4 Begins Here

//foursome4 Ends Here
?><?php
//foursome4 Begins Here

//foursome4 Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//leftbar Begins Here

//leftbar Ends Here
?><?php
//leftbar Begins Here

//leftbar Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-8 8u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//leftbarright Begins Here

//leftbarright Ends Here
?><?php
//leftbarright Begins Here

//leftbarright Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-8 8u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//rightbarleft Begins Here

//rightbarleft Ends Here
?><?php
//rightbarleft Begins Here

//rightbarleft Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//rightbar Begins Here

//rightbar Ends Here
?><?php
//rightbar Begins Here

//rightbar Ends Here
?>
											</div>   
										</div> 
									</div> 
								</section><?php
//lastoneness Begins Here

//lastoneness Ends Here
?><?php
//lastoneness Begins Here

//lastoneness Ends Here
?></section>
<?php
//row_one Begins Here

//row_one Ends Here
?><?php
//row_one Begins Here

//row_one Ends Here
?>



<?php
//charts Begins Here

//charts Ends Here
?><?php
//charts Begins Here

//charts Ends Here
?>



<?php
//three Begins Here

//three Ends Here
?><?php
//three Begins Here

//three Ends Here
?>



<?php
//four Begins Here

//four Ends Here
?><?php
//four Begins Here

//four Ends Here
?>



<?php
//five Begins Here

//five Ends Here
?><?php
//five Begins Here

//five Ends Here
?>


<div class="clearfix"> </div>
			</div>
		</div>
		<!--footer-->
			<div class="main-page" data-pc-section-autonamed="4" data-pc-section-name="pc-body-4">
		<div class="footer">
		
<?php
//footer Begins Here

//footer Ends Here
?><?php
//footer Begins Here

echo ( ! empty( $_2b0ebdfee9b736d01f4e00b5169f0eb1 ) &&  is_object( $_2b0ebdfee9b736d01f4e00b5169f0eb1 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_2b0ebdfee9b736d01f4e00b5169f0eb1->view(), '' ) : null );

//footer Ends Here
?>



</div>
		</div>
        <!--//footer-->
	</div>
	<!-- Classie -->
		<script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/classie.js"></script><script>
			var menuLeft = document.getElementById( 'cbp-spmenu-s1' ),
				showLeftPush = document.getElementById( 'showLeftPush' ),
				body = document.body;
				
			showLeftPush.onclick = function() {
				classie.toggle( this, 'active' );
				classie.toggle( body, 'cbp-spmenu-push-toright' );
				classie.toggle( menuLeft, 'cbp-spmenu-open' );
				disableOther( 'showLeftPush' );
			};
			

			function disableOther( button ) {
				if( button !== 'showLeftPush' ) {
					classie.toggle( showLeftPush, 'disabled' );
				}
			}
		</script><!--scrolling js--><script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/jquery.nicescroll.js"></script><script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/scripts.js"></script><!--//scrolling js--><!-- Bootstrap Core JavaScript --><script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/novus/js/bootstrap.js"> </script><?php include_once( LAYOUT_PATH . DS . 'footerJs' . TPL ) ?><?php include_once( LAYOUT_PATH . DS . 'footer' . TPL ) ?>
</body>
</html>
