<?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /pc-tutorials
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: pc-tutorials.php	Thursday 25th of July 2019 10:42:35 PM	ayoola@ayoo.la $ 
*/
//	Template Content ?>

						<?php 
						//		var_export( array_pop( explode( PC_BASE, Ayoola_Application::getDomainSettings( APPLICATION_PATH ) ) ) );
					//			var_export( __FILE__ );
					//			var_export( CACHE_DIR );
					//			var_export( stripos( __FILE__, Ayoola_Application::getDomainSettings( APPLICATION_DIR ) ) );
								//	ADDED TO CHECK WITH CACHE_DIR TOO BECAUSE OF EDITING THEME PAGES
								//	THEY WON'T HAVE CORRECT APPDIR
//								var_export( stripos( __FILE__,CACHE_DIR ) );
			//					var_export( Ayoola_Application::getDomainSettings( APPLICATION_DIR ) );
			//					var_export( Ayoola_Application::getDomainSettings() );
							if
							( 

								$x_1564094555 = Ayoola_Filter_LayoutIdToPath::getThemeIncludeFile( 'bootstrapbasic', stripos( __FILE__, Ayoola_Application::getDomainSettings( APPLICATION_DIR ) ) !== false || stripos( __FILE__,CACHE_DIR ) !== false ? array( 'prioritize_my_copy' => true, 'multiple' => true,  ) : array( 'path_blacklist' => array_pop( explode( PC_BASE, Ayoola_Application::getDomainSettings( APPLICATION_PATH ) ) ), 'multiple' => true ) ) 
							)
							{
							//	var_export( $x_1564094555 );
							//	echo file_get_contents( $x_1564094555 );
								foreach( $x_1564094555 as $each )
								{	
									include_once $each;
								}
							}
		//					var_export( $x_1564094555 );
						?>
						 <?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /layout/bootstrapbasic/template
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: template.php	Thursday 25th of July 2019 10:42:34 PM	ayoola@ayoo.la $ 
*/
//	Template Content ?>
<!DOCTYPE html>
<html lang="en">
<head>
<?php include_once( LAYOUT_PATH . DS . 'htmlHeader' . TPL ) ?>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="author" content="">
<!-- Bootstrap Core CSS --><link href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/bootstrapbasic/css/bootstrap.min.css" rel="stylesheet">
<!-- Custom CSS --><link href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/bootstrapbasic/css/small-business.css" rel="stylesheet">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries --><!-- WARNING: Respond.js doesn't work if you view the page via file:// --><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]--><link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>
<body style="background-color: #ddd;" data-pc-section-name="body">
<?php include_once( LAYOUT_PATH . DS . 'header' . TPL ) ?>

    <!-- Navigation -->
<nav id="mainnav" class="navbar navbar-inverse navbar-fixed-top" role="navigation" data-pc-menu-id-list=",bs-example-navbar-collapse-1" data-pc-menu-ul-class-bs-example-navbar-collapse-1="nav navbar-nav navbar-right" data-pc-menu-li-active-class-bs-example-navbar-collapse-1="dropdown" data-pc-menu-li-ul-class-bs-example-navbar-collapse-1="dropdown-menu"><div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar">&nbsp;</span>
                    <span class="icon-bar">&nbsp;</span>
                    <span class="icon-bar">&nbsp;</span>
                </button>
                <a class="navbar-brand" style="height:auto;height:initial;height:unset;" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/"><img style="max-height:50px;" name="pc-logo" src="<?php echo Ayoola_Doc::getLogo(); ?>"></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <?php echo Ayoola_Menu_Demo::viewInLine( array( 'option' => 'mainnav', 'li-active-class' => 'dropdown', 'ul-class' => 'nav navbar-nav navbar-right', 'ul-id' => '', )  ); ?>
</div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav><!-- Page Content --><div class="container" data-pc-section-autonamed="1" data-pc-section-name="pc-body-1">

        <!-- Heading Row -->
		<?php
//oneness Begins Here

echo ( ! empty( $_e3acf1a6d0ebcd48a43915385589e71e ) &&  is_object( $_e3acf1a6d0ebcd48a43915385589e71e ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_e3acf1a6d0ebcd48a43915385589e71e->view(), '' ) : null );

//oneness Ends Here
?><?php
//oneness Begins Here

//oneness Ends Here
?><section data-pc-all-sections="1">	
									<div class="">
										<div class="row">
											<div class="pc_page_layout_grid col-md-12 12u">
												<?php
//middlebar Begins Here

//middlebar Ends Here
?><?php
//middlebar Begins Here

echo ( ! empty( $_7e559ca9f527527b35db37ac74db2c6d ) &&  is_object( $_7e559ca9f527527b35db37ac74db2c6d ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_7e559ca9f527527b35db37ac74db2c6d->view(), '' ) : null );

//middlebar Ends Here
?>
										   </div>
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-6 6u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//twosome1 Begins Here

//twosome1 Ends Here
?><?php
//twosome1 Begins Here

//twosome1 Ends Here
?>
											</div>
											<div class="pc_page_layout_grid col-sm-6 6u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//twosome2 Begins Here

//twosome2 Ends Here
?><?php
//twosome2 Begins Here

//twosome2 Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)"> 
												<?php
//threesome1 Begins Here

//threesome1 Ends Here
?><?php
//threesome1 Begins Here

//threesome1 Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//threesome2 Begins Here

//threesome2 Ends Here
?><?php
//threesome2 Begins Here

//threesome2 Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//threesome3 Begins Here

//threesome3 Ends Here
?><?php
//threesome3 Begins Here

//threesome3 Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome1 Begins Here

//foursome1 Ends Here
?><?php
//foursome1 Begins Here

//foursome1 Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome2 Begins Here

//foursome2 Ends Here
?><?php
//foursome2 Begins Here

//foursome2 Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-3 3u 6u(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome3 Begins Here

//foursome3 Ends Here
?><?php
//foursome3 Begins Here

//foursome3 Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">    
												<?php
//foursome4 Begins Here

//foursome4 Ends Here
?><?php
//foursome4 Begins Here

//foursome4 Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//leftbar Begins Here

//leftbar Ends Here
?><?php
//leftbar Begins Here

//leftbar Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-8 8u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//leftbarright Begins Here

//leftbarright Ends Here
?><?php
//leftbarright Begins Here

//leftbarright Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-8 8u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//rightbarleft Begins Here

//rightbarleft Ends Here
?><?php
//rightbarleft Begins Here

//rightbarleft Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//rightbar Begins Here

//rightbar Ends Here
?><?php
//rightbar Begins Here

//rightbar Ends Here
?>
											</div>   
										</div> 
									</div> 
								</section><?php
//lastoneness Begins Here

//lastoneness Ends Here
?><?php
//lastoneness Begins Here

//lastoneness Ends Here
?>
<?php
//pc_body_1 Begins Here

//pc_body_1 Ends Here
?><?php
//pc_body_1 Begins Here

//pc_body_1 Ends Here
?>



        <!-- /.row -->

        <hr>
<!-- Call to Action Well -->
<?php
//pc_body_2 Begins Here

//pc_body_2 Ends Here
?><?php
//pc_body_2 Begins Here

//pc_body_2 Ends Here
?>


<!-- /.row --><!-- Content Row -->
<?php
//pc_body_3 Begins Here

//pc_body_3 Ends Here
?><?php
//pc_body_3 Begins Here

//pc_body_3 Ends Here
?>



        <!-- /.row -->

        <!-- Footer -->
        
<?php
//pc_body_4 Begins Here

//pc_body_4 Ends Here
?><?php
//pc_body_4 Begins Here

//pc_body_4 Ends Here
?>



</div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/bootstrapbasic/js/jquery.js"></script><!-- Bootstrap Core JavaScript --><script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/bootstrapbasic/js/bootstrap.min.js"></script><?php include_once( LAYOUT_PATH . DS . 'footerJs' . TPL ) ?><?php include_once( LAYOUT_PATH . DS . 'footer' . TPL ) ?>
</body>
</html>
