<?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /profile
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: profile.php	Friday 17th of June 2022 02:33:42 PM	joywealth@hotmail.com $ 
*/
//	Template Content ?>

                    <?php 

                            //	ADDED TO CHECK WITH CACHE_DIR TOO BECAUSE OF EDITING THEME PAGES
                            //	THEY WON'T HAVE CORRECT APPDIR
                        if
                        ( 

                            $x_1655476422 = Ayoola_Filter_LayoutIdToPath::getThemeIncludeFile( 'pc_layout_miniblog', stripos( __FILE__, Ayoola_Application::getDomainSettings( APPLICATION_DIR ) ) !== false || stripos( __FILE__,CACHE_DIR ) !== false ? array( 'prioritize_my_copy' => true, 'multiple' => true,  ) : array( 'path_blacklist' => @array_pop( explode( PC_BASE, Ayoola_Application::getDomainSettings( APPLICATION_PATH ) ) ), 'multiple' => true ) ) 
                        )
                        {

                            if( $x_1655476422 )
                            foreach( $x_1655476422 as $each )
                            {	
                                include_once $each;
                            }
                        }

                    ?>
                     <?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /default-layout
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: default-layout.php	Friday 17th of June 2022 02:33:38 PM	joywealth@hotmail.com $ 
*/
//	Template Content ?>

                    <?php 

                            //	ADDED TO CHECK WITH CACHE_DIR TOO BECAUSE OF EDITING THEME PAGES
                            //	THEY WON'T HAVE CORRECT APPDIR
                        if
                        ( 

                            $x_1655476418 = Ayoola_Filter_LayoutIdToPath::getThemeIncludeFile( 'pc_layout_miniblog', stripos( __FILE__, Ayoola_Application::getDomainSettings( APPLICATION_DIR ) ) !== false || stripos( __FILE__,CACHE_DIR ) !== false ? array( 'prioritize_my_copy' => true, 'multiple' => true,  ) : array( 'path_blacklist' => @array_pop( explode( PC_BASE, Ayoola_Application::getDomainSettings( APPLICATION_PATH ) ) ), 'multiple' => true ) ) 
                        )
                        {

                            if( $x_1655476418 )
                            foreach( $x_1655476418 as $each )
                            {	
                                include_once $each;
                            }
                        }

                    ?>
                     <?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /layout/pc_layout_miniblog/template
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: template.php	Friday 17th of June 2022 12:42:19 PM	projects@comeriver.com $ 
*/
//	Template Content ?>
<!DOCTYPE html>
<html lang="en">
  <head>
<?php include_once( LAYOUT_PATH . DS . 'htmlHeader' . TPL ) ?>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,700%7CPlayfair+Display:400,700,900" rel="stylesheet">

    <link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/fonts/icomoon/style.css">
    <link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/css/magnific-popup.css">
    <link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/css/jquery-ui.css">
    <link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/css/owl.carousel.min.css">
    <link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/fonts/flaticon/font/flaticon.css">
    <link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/css/aos.css">

    <link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/css/style.css"> 
  </head>
  <body data-pc-section-name="body">
<?php include_once( LAYOUT_PATH . DS . 'header' . TPL ) ?>

  <div class="site-wrap" data-pc-section-autonamed="1" data-pc-section-name="pc-body-1">

    <?php
//pc_body_2 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_pc_body_2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//pc_body_2 /layout/pc_layout_miniblog/template Ends Here
?><?php
//pc_body_2 /default-layout Begins Here

					if( empty( $_a6bab01c3343c87b57263e96fe4b393b ) || ! is_object( $_a6bab01c3343c87b57263e96fe4b393b ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_a6bab01c3343c87b57263e96fe4b393b, '' );

					
//pc_body_2 /default-layout Ends Here
?><?php
//pc_body_2 /profile Begins Here

//pc_body_2 /profile Ends Here
?>

    <?php
//pc_body_3 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_pc_body_3 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
					if( empty( $_d76bf097f38f533b4a962980bc13892a ) || ! is_object( $_d76bf097f38f533b4a962980bc13892a ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_d76bf097f38f533b4a962980bc13892a, '' );

					
//pc_body_3 /layout/pc_layout_miniblog/template Ends Here
?><?php
//pc_body_3 /default-layout Begins Here

//pc_body_3 /default-layout Ends Here
?><?php
//pc_body_3 /profile Begins Here

//pc_body_3 /profile Ends Here
?><?php
//oneness /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_oneness as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//oneness /layout/pc_layout_miniblog/template Ends Here
?><?php
//oneness /default-layout Begins Here

//oneness /default-layout Ends Here
?><?php
//oneness /profile Begins Here

//oneness /profile Ends Here
?><section data-pc-all-sections="1" class="container">	
									<div class="">
										<div class="row">
											<div class="pc_page_layout_grid col-md-12 12u">
												<?php
//middlebar /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_middlebar as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//middlebar /layout/pc_layout_miniblog/template Ends Here
?><?php
//middlebar /default-layout Begins Here

//middlebar /default-layout Ends Here
?><?php
//middlebar /profile Begins Here

					if( empty( $_5624cf8c5adba1f8d7bdb295e1423e72 ) || ! is_object( $_5624cf8c5adba1f8d7bdb295e1423e72 ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_5624cf8c5adba1f8d7bdb295e1423e72, '' );

					
					if( empty( $_4271e658c6bccc97ba5b3cf6db86f81a ) || ! is_object( $_4271e658c6bccc97ba5b3cf6db86f81a ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_4271e658c6bccc97ba5b3cf6db86f81a, 'well' );

					
					if( empty( $_51ad269b2804228e073d6ded3588f388 ) || ! is_object( $_51ad269b2804228e073d6ded3588f388 ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_51ad269b2804228e073d6ded3588f388, '' );

					
//middlebar /profile Ends Here
?>
										   </div>
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-6 6u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//twosome1 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_twosome1 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//twosome1 /layout/pc_layout_miniblog/template Ends Here
?><?php
//twosome1 /default-layout Begins Here

//twosome1 /default-layout Ends Here
?><?php
//twosome1 /profile Begins Here

					if( empty( $_166a149c8ae9cfb5621fc376dd6613a1 ) || ! is_object( $_166a149c8ae9cfb5621fc376dd6613a1 ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_166a149c8ae9cfb5621fc376dd6613a1, 'white-well' );

					
//twosome1 /profile Ends Here
?>
											</div>
											<div class="pc_page_layout_grid col-sm-6 6u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//twosome2 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_twosome2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//twosome2 /layout/pc_layout_miniblog/template Ends Here
?><?php
//twosome2 /default-layout Begins Here

//twosome2 /default-layout Ends Here
?><?php
//twosome2 /profile Begins Here

					if( empty( $_d41c138d6ef884c18d72b5e988f6e6c2 ) || ! is_object( $_d41c138d6ef884c18d72b5e988f6e6c2 ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_d41c138d6ef884c18d72b5e988f6e6c2, 'well' );

					
//twosome2 /profile Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)"> 
												<?php
//threesome1 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_threesome1 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//threesome1 /layout/pc_layout_miniblog/template Ends Here
?><?php
//threesome1 /default-layout Begins Here

//threesome1 /default-layout Ends Here
?><?php
//threesome1 /profile Begins Here

//threesome1 /profile Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//threesome2 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_threesome2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//threesome2 /layout/pc_layout_miniblog/template Ends Here
?><?php
//threesome2 /default-layout Begins Here

//threesome2 /default-layout Ends Here
?><?php
//threesome2 /profile Begins Here

//threesome2 /profile Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//threesome3 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_threesome3 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//threesome3 /layout/pc_layout_miniblog/template Ends Here
?><?php
//threesome3 /default-layout Begins Here

//threesome3 /default-layout Ends Here
?><?php
//threesome3 /profile Begins Here

//threesome3 /profile Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome1 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_foursome1 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome1 /layout/pc_layout_miniblog/template Ends Here
?><?php
//foursome1 /default-layout Begins Here

//foursome1 /default-layout Ends Here
?><?php
//foursome1 /profile Begins Here

//foursome1 /profile Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome2 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_foursome2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome2 /layout/pc_layout_miniblog/template Ends Here
?><?php
//foursome2 /default-layout Begins Here

//foursome2 /default-layout Ends Here
?><?php
//foursome2 /profile Begins Here

//foursome2 /profile Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-3 3u 6u(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome3 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_foursome3 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome3 /layout/pc_layout_miniblog/template Ends Here
?><?php
//foursome3 /default-layout Begins Here

//foursome3 /default-layout Ends Here
?><?php
//foursome3 /profile Begins Here

//foursome3 /profile Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">    
												<?php
//foursome4 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_foursome4 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome4 /layout/pc_layout_miniblog/template Ends Here
?><?php
//foursome4 /default-layout Begins Here

//foursome4 /default-layout Ends Here
?><?php
//foursome4 /profile Begins Here

//foursome4 /profile Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//leftbar /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_leftbar as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//leftbar /layout/pc_layout_miniblog/template Ends Here
?><?php
//leftbar /default-layout Begins Here

//leftbar /default-layout Ends Here
?><?php
//leftbar /profile Begins Here

//leftbar /profile Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-8 8u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//leftbarright /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_leftbarright as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//leftbarright /layout/pc_layout_miniblog/template Ends Here
?><?php
//leftbarright /default-layout Begins Here

//leftbarright /default-layout Ends Here
?><?php
//leftbarright /profile Begins Here

//leftbarright /profile Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-8 8u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//rightbarleft /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_rightbarleft as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//rightbarleft /layout/pc_layout_miniblog/template Ends Here
?><?php
//rightbarleft /default-layout Begins Here

//rightbarleft /default-layout Ends Here
?><?php
//rightbarleft /profile Begins Here

//rightbarleft /profile Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//rightbar /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_rightbar as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//rightbar /layout/pc_layout_miniblog/template Ends Here
?><?php
//rightbar /default-layout Begins Here

//rightbar /default-layout Ends Here
?><?php
//rightbar /profile Begins Here

//rightbar /profile Ends Here
?>
											</div>   
										</div> 
									</div> 
									</section><?php
//lastoneness /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_lastoneness as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//lastoneness /layout/pc_layout_miniblog/template Ends Here
?><?php
//lastoneness /default-layout Begins Here

//lastoneness /default-layout Ends Here
?><?php
//lastoneness /profile Begins Here

					if( empty( $_5b583620a69a1074ce34c80deaf8c812 ) || ! is_object( $_5b583620a69a1074ce34c80deaf8c812 ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_5b583620a69a1074ce34c80deaf8c812, '' );

					
					if( empty( $_007a086925f4447b298f90a895538b81 ) || ! is_object( $_007a086925f4447b298f90a895538b81 ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_007a086925f4447b298f90a895538b81, '' );

					
//lastoneness /profile Ends Here
?>    

    <?php
//pc_body_4 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_pc_body_4 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//pc_body_4 /layout/pc_layout_miniblog/template Ends Here
?><?php
//pc_body_4 /default-layout Begins Here

					if( empty( $_f08919130e564f1d757a848674a358d7 ) || ! is_object( $_f08919130e564f1d757a848674a358d7 ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_f08919130e564f1d757a848674a358d7, '' );

					
//pc_body_4 /default-layout Ends Here
?><?php
//pc_body_4 /profile Begins Here

//pc_body_4 /profile Ends Here
?>

    <?php
//pc_body_5 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_pc_body_5 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//pc_body_5 /layout/pc_layout_miniblog/template Ends Here
?><?php
//pc_body_5 /default-layout Begins Here

//pc_body_5 /default-layout Ends Here
?><?php
//pc_body_5 /profile Begins Here

//pc_body_5 /profile Ends Here
?>

    <?php
//pc_body_6 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_pc_body_6 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//pc_body_6 /layout/pc_layout_miniblog/template Ends Here
?><?php
//pc_body_6 /default-layout Begins Here

//pc_body_6 /default-layout Ends Here
?><?php
//pc_body_6 /profile Begins Here

//pc_body_6 /profile Ends Here
?>

    <?php
//pc_body_7 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_pc_body_7 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//pc_body_7 /layout/pc_layout_miniblog/template Ends Here
?><?php
//pc_body_7 /default-layout Begins Here

//pc_body_7 /default-layout Ends Here
?><?php
//pc_body_7 /profile Begins Here

//pc_body_7 /profile Ends Here
?>

    <?php
//pc_body_8 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_pc_body_8 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
					if( empty( $_274f1f7e068d8ec9b8ec0a58942072c2 ) || ! is_object( $_274f1f7e068d8ec9b8ec0a58942072c2 ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_274f1f7e068d8ec9b8ec0a58942072c2, '' );

					
//pc_body_8 /layout/pc_layout_miniblog/template Ends Here
?><?php
//pc_body_8 /default-layout Begins Here

//pc_body_8 /default-layout Ends Here
?><?php
//pc_body_8 /profile Begins Here

//pc_body_8 /profile Ends Here
?>

  </div>

  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/jquery-3.3.1.min.js"></script>
  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/jquery-migrate-3.0.1.min.js"></script>
  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/jquery-ui.js"></script>
  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/popper.min.js"></script>
  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/bootstrap.min.js"></script>
  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/owl.carousel.min.js"></script>
  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/jquery.stellar.min.js"></script>
  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/jquery.countdown.min.js"></script>
  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/jquery.magnific-popup.min.js"></script>
  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/bootstrap-datepicker.min.js"></script>
  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/aos.js"></script>

  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/main.js"></script>

  <?php include_once( LAYOUT_PATH . DS . 'footerJs' . TPL ) ?><?php include_once( LAYOUT_PATH . DS . 'footer' . TPL ) ?><?php
//pc_section_after_js /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_pc_section_after_js as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//pc_section_after_js /layout/pc_layout_miniblog/template Ends Here
?><?php
//pc_section_after_js /default-layout Begins Here

//pc_section_after_js /default-layout Ends Here
?><?php
//pc_section_after_js /profile Begins Here

//pc_section_after_js /profile Ends Here
?>
</body>
</html>
