<?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /onlinestore/confirmation
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: confirmation.php	Saturday 16th of September 2017 10:58:56 PM	 $ 
*/
//	Template Content ?>

						<?php 
							if
							( 
								$x_1505602736 = Ayoola_Filter_LayoutIdToPath::getThemeIncludeFile( 'bootstrapbasic', array( 'prioritize_my_copy' => true ) ) 
							)
							{
								include_once $x_1505602736;
							}
						?>
						 <?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /layout/bootstrapbasic/template
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: template.php	Saturday 16th of September 2017 10:58:45 PM	 $ 
*/
//	Template Content ?>
<!DOCTYPE html>
<html lang="en">
<head>
<?php include_once( LAYOUT_PATH . DS . 'htmlHeader' . TPL ) ?>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="author" content="">
<!-- Bootstrap Core CSS --><link href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/bootstrapbasic/css/bootstrap.min.css" rel="stylesheet">
<!-- Custom CSS --><link href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/bootstrapbasic/css/small-business.css" rel="stylesheet">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries --><!-- WARNING: Respond.js doesn't work if you view the page via file:// --><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]--><link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>
<body style="background-color: #ddd;" data-pc-section-name="body">

    <!-- Navigation -->
<nav id="mainnav" class="navbar navbar-inverse navbar-fixed-top" role="navigation" data-pc-menu-id-list=",bs-example-navbar-collapse-1" data-pc-menu-ul-class-bs-example-navbar-collapse-1="nav navbar-nav navbar-right" data-pc-menu-li-active-class-bs-example-navbar-collapse-1="dropdown" data-pc-menu-li-ul-class-bs-example-navbar-collapse-1="dropdown-menu"><div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar">&nbsp;</span>
                    <span class="icon-bar">&nbsp;</span>
                    <span class="icon-bar">&nbsp;</span>
                </button>
                <a class="navbar-brand" style="height:auto;height:initial;height:unset;" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/"><img style="max-height:50px;" name="pc-logo" src="<?php echo Ayoola_Doc::getLogo(); ?>"></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <?php echo Ayoola_Menu_Demo::viewInLine( array( 'option' => 'mainnav', 'li-active-class' => 'dropdown', 'ul-class' => 'nav navbar-nav navbar-right', 'ul-id' => '', )  ); ?>
</div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav><!-- Page Content --><div class="container" data-pc-section-autonamed="1" data-pc-section-name="pc-body-1">

        <!-- Heading Row -->
		<section data-pc-all-sections="1">	
									<?php
//oneness Begins Here

echo ( ! empty( $_b7050bae07234eabc14cec6521a7fe97 ) &&  is_object( $_b7050bae07234eabc14cec6521a7fe97 ) ? Ayoola_Object_Wrapper_Abstract::wrap( $_b7050bae07234eabc14cec6521a7fe97->view(), '' ) : null );

//oneness Ends Here
?><?php
//oneness Begins Here

//oneness Ends Here
?>
									<div class="">
										<div class="row">
											<div class="col-lg-12 12u">
												<?php
//middlebar Begins Here

//middlebar Ends Here
?><?php
//middlebar Begins Here

//middlebar Ends Here
?>
										   </div>
										</div> 
										<div class="row">
											<div class="col-lg-6 6u 6u(medium) 12u$(xsmall)">
												<?php
//twosome1 Begins Here

//twosome1 Ends Here
?><?php
//twosome1 Begins Here

//twosome1 Ends Here
?>
											</div>
											<div class="col-lg-6 6u 6u(medium) 12u$(xsmall)">
												<?php
//twosome2 Begins Here

//twosome2 Ends Here
?><?php
//twosome2 Begins Here

//twosome2 Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="col-lg-4 4u 12u$(medium) 12u$(xsmall)"> 
												<?php
//threesome1 Begins Here

//threesome1 Ends Here
?><?php
//threesome1 Begins Here

//threesome1 Ends Here
?>
										   </div>
											<div class="col-lg-4 4u 12u$(medium) 12u$(xsmall)">
												<?php
//threesome2 Begins Here

//threesome2 Ends Here
?><?php
//threesome2 Begins Here

//threesome2 Ends Here
?>
											</div> 
											<div class="col-lg-4 4u 12u$(medium) 12u$(xsmall)">
												<?php
//threesome3 Begins Here

//threesome3 Ends Here
?><?php
//threesome3 Begins Here

//threesome3 Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="col-lg-3 3u 6u(medium) 12u$(xsmall)">
												<?php
//foursome1 Begins Here

//foursome1 Ends Here
?><?php
//foursome1 Begins Here

//foursome1 Ends Here
?>
										   </div>
											<div class="col-lg-3 3u 6u$(medium) 12u$(xsmall)">
												<?php
//foursome2 Begins Here

//foursome2 Ends Here
?><?php
//foursome2 Begins Here

//foursome2 Ends Here
?>
											</div> 
											<div class="col-lg-3 3u 6u(medium) 12u$(xsmall)">
												<?php
//foursome3 Begins Here

//foursome3 Ends Here
?><?php
//foursome3 Begins Here

//foursome3 Ends Here
?>
											</div> 
											<div class="col-lg-3 3u 6u$(medium) 12u$(xsmall)">    
												<?php
//foursome4 Begins Here

//foursome4 Ends Here
?><?php
//foursome4 Begins Here

//foursome4 Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="col-lg-4 4u 12u$(medium) 12u$(xsmall)">
												<?php
//leftbar Begins Here

//leftbar Ends Here
?><?php
//leftbar Begins Here

//leftbar Ends Here
?>
										   </div>
											<div class="col-lg-8 8u 12u$(medium) 12u$(xsmall)">
												<?php
//leftbarright Begins Here

//leftbarright Ends Here
?><?php
//leftbarright Begins Here

//leftbarright Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="col-lg-8 8u 12u$(medium) 12u$(xsmall)">
												<?php
//rightbarleft Begins Here

//rightbarleft Ends Here
?><?php
//rightbarleft Begins Here

//rightbarleft Ends Here
?>
											</div> 
											<div class="col-lg-4 4u 12u$(medium) 12u$(xsmall)">
												<?php
//rightbar Begins Here

//rightbar Ends Here
?><?php
//rightbar Begins Here

//rightbar Ends Here
?>
											</div>   
										</div> 
									</div> 
									<?php
//lastoneness Begins Here

//lastoneness Ends Here
?><?php
//lastoneness Begins Here

//lastoneness Ends Here
?>
								</section><div class="row" data-pc-section-autonamed="1" data-pc-section-name="pc-body-1">
		
<?php
//headline Begins Here

//headline Ends Here
?><?php
//headline Begins Here

//headline Ends Here
?>



</div>
        <!-- /.row -->

        <hr>
<!-- Call to Action Well -->
<?php
//actionwell Begins Here

//actionwell Ends Here
?><?php
//actionwell Begins Here

//actionwell Ends Here
?>


<!-- /.row --><!-- Content Row --><div class="row" data-pc-section-autonamed="3" data-pc-section-name="pc-body-3">
 		
<?php
//content Begins Here

//content Ends Here
?><?php
//content Begins Here

//content Ends Here
?>



</div>
        <!-- /.row -->

        <!-- Footer -->
        
<?php
//footer Begins Here

//footer Ends Here
?><?php
//footer Begins Here

//footer Ends Here
?>



</div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/bootstrapbasic/js/jquery.js"></script><!-- Bootstrap Core JavaScript --><script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/bootstrapbasic/js/bootstrap.min.js"></script><?php include_once( LAYOUT_PATH . DS . 'footerJs' . TPL ) ?>
</body>
</html>
