<?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /post/view
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: view.php	Friday 17th of June 2022 12:50:24 PM	projects@comeriver.com $ 
*/
//	Template Content ?>

                    <?php 

                            //	ADDED TO CHECK WITH CACHE_DIR TOO BECAUSE OF EDITING THEME PAGES
                            //	THEY WON'T HAVE CORRECT APPDIR
                        if
                        ( 

                            $x_1655470224 = Ayoola_Filter_LayoutIdToPath::getThemeIncludeFile( 'pc_layout_miniblog', stripos( __FILE__, Ayoola_Application::getDomainSettings( APPLICATION_DIR ) ) !== false || stripos( __FILE__,CACHE_DIR ) !== false ? array( 'prioritize_my_copy' => true, 'multiple' => true,  ) : array( 'path_blacklist' => @array_pop( explode( PC_BASE, Ayoola_Application::getDomainSettings( APPLICATION_PATH ) ) ), 'multiple' => true ) ) 
                        )
                        {

                            if( $x_1655470224 )
                            foreach( $x_1655470224 as $each )
                            {	
                                include_once $each;
                            }
                        }

                    ?>
                     <?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /default-layout
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: default-layout.php	Friday 17th of June 2022 12:50:18 PM	projects@comeriver.com $ 
*/
//	Template Content ?>

                    <?php 

                            //	ADDED TO CHECK WITH CACHE_DIR TOO BECAUSE OF EDITING THEME PAGES
                            //	THEY WON'T HAVE CORRECT APPDIR
                        if
                        ( 

                            $x_1655470218 = Ayoola_Filter_LayoutIdToPath::getThemeIncludeFile( 'pc_layout_miniblog', stripos( __FILE__, Ayoola_Application::getDomainSettings( APPLICATION_DIR ) ) !== false || stripos( __FILE__,CACHE_DIR ) !== false ? array( 'prioritize_my_copy' => true, 'multiple' => true,  ) : array( 'path_blacklist' => @array_pop( explode( PC_BASE, Ayoola_Application::getDomainSettings( APPLICATION_PATH ) ) ), 'multiple' => true ) ) 
                        )
                        {

                            if( $x_1655470218 )
                            foreach( $x_1655470218 as $each )
                            {	
                                include_once $each;
                            }
                        }

                    ?>
                     <?php
/**
* PageCarton Page Generator
*
* LICENSE
*
* @category PageCarton
* @package /layout/pc_layout_miniblog/template
* @generated Ayoola_Page_Editor_Layout
* @copyright  Copyright (c) PageCarton. (http://www.PageCarton.com)
* @license    http://www.PageCarton.com/license.txt
* @version $Id: template.php	Friday 17th of June 2022 12:42:19 PM	projects@comeriver.com $ 
*/
//	Template Content ?>
<!DOCTYPE html>
<html lang="en">
  <head>
<?php include_once( LAYOUT_PATH . DS . 'htmlHeader' . TPL ) ?>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,700%7CPlayfair+Display:400,700,900" rel="stylesheet">

    <link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/fonts/icomoon/style.css">
    <link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/css/magnific-popup.css">
    <link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/css/jquery-ui.css">
    <link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/css/owl.carousel.min.css">
    <link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/fonts/flaticon/font/flaticon.css">
    <link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/css/aos.css">

    <link rel="stylesheet" href="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/css/style.css"> 
  </head>
  <body data-pc-section-name="body">
<?php include_once( LAYOUT_PATH . DS . 'header' . TPL ) ?>

  <div class="site-wrap" data-pc-section-autonamed="1" data-pc-section-name="pc-body-1">

    <?php
//pc_body_2 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_pc_body_2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//pc_body_2 /layout/pc_layout_miniblog/template Ends Here
?><?php
//pc_body_2 /default-layout Begins Here

					if( empty( $_a6bab01c3343c87b57263e96fe4b393b ) || ! is_object( $_a6bab01c3343c87b57263e96fe4b393b ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_a6bab01c3343c87b57263e96fe4b393b, '' );

					
//pc_body_2 /default-layout Ends Here
?><?php
//pc_body_2 /post/view Begins Here

//pc_body_2 /post/view Ends Here
?>

    <?php
//pc_body_3 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_pc_body_3 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
					if( empty( $_d76bf097f38f533b4a962980bc13892a ) || ! is_object( $_d76bf097f38f533b4a962980bc13892a ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_d76bf097f38f533b4a962980bc13892a, '' );

					
//pc_body_3 /layout/pc_layout_miniblog/template Ends Here
?><?php
//pc_body_3 /default-layout Begins Here

//pc_body_3 /default-layout Ends Here
?><?php
//pc_body_3 /post/view Begins Here

//pc_body_3 /post/view Ends Here
?><?php
//oneness /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_oneness as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//oneness /layout/pc_layout_miniblog/template Ends Here
?><?php
//oneness /default-layout Begins Here

//oneness /default-layout Ends Here
?><?php
//oneness /post/view Begins Here

//oneness /post/view Ends Here
?><section data-pc-all-sections="1" class="container">	
									<div class="">
										<div class="row">
											<div class="pc_page_layout_grid col-md-12 12u">
												<?php
//middlebar /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_middlebar as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//middlebar /layout/pc_layout_miniblog/template Ends Here
?><?php
//middlebar /default-layout Begins Here

//middlebar /default-layout Ends Here
?><?php
//middlebar /post/view Begins Here

					if( empty( $_8eccaa7e0a95bfe06f5ebffc31ee8f0f ) || ! is_object( $_8eccaa7e0a95bfe06f5ebffc31ee8f0f ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_8eccaa7e0a95bfe06f5ebffc31ee8f0f, '' );

					
//middlebar /post/view Ends Here
?>
										   </div>
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-6 6u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//twosome1 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_twosome1 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//twosome1 /layout/pc_layout_miniblog/template Ends Here
?><?php
//twosome1 /default-layout Begins Here

//twosome1 /default-layout Ends Here
?><?php
//twosome1 /post/view Begins Here

					if( empty( $_85c670985c03815dd9f45362c1c9b988 ) || ! is_object( $_85c670985c03815dd9f45362c1c9b988 ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_85c670985c03815dd9f45362c1c9b988, 'well' );

					
					if( empty( $_b107e295260b4f99579dc21f30ce47cb ) || ! is_object( $_b107e295260b4f99579dc21f30ce47cb ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_b107e295260b4f99579dc21f30ce47cb, '' );

					
					if( empty( $_2ef3917fcdce6be10601f99ac5e4d1ac ) || ! is_object( $_2ef3917fcdce6be10601f99ac5e4d1ac ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_2ef3917fcdce6be10601f99ac5e4d1ac, 'well' );

					
//twosome1 /post/view Ends Here
?>
											</div>
											<div class="pc_page_layout_grid col-sm-6 6u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//twosome2 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_twosome2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//twosome2 /layout/pc_layout_miniblog/template Ends Here
?><?php
//twosome2 /default-layout Begins Here

//twosome2 /default-layout Ends Here
?><?php
//twosome2 /post/view Begins Here

					if( empty( $_034db1ec16982a829003894d7fbb2d91 ) || ! is_object( $_034db1ec16982a829003894d7fbb2d91 ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_034db1ec16982a829003894d7fbb2d91, '' );

					
					if( empty( $_c117484efadc0829f15ead54700c8d4e ) || ! is_object( $_c117484efadc0829f15ead54700c8d4e ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_c117484efadc0829f15ead54700c8d4e, '' );

					
//twosome2 /post/view Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)"> 
												<?php
//threesome1 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_threesome1 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//threesome1 /layout/pc_layout_miniblog/template Ends Here
?><?php
//threesome1 /default-layout Begins Here

//threesome1 /default-layout Ends Here
?><?php
//threesome1 /post/view Begins Here

//threesome1 /post/view Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//threesome2 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_threesome2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//threesome2 /layout/pc_layout_miniblog/template Ends Here
?><?php
//threesome2 /default-layout Begins Here

//threesome2 /default-layout Ends Here
?><?php
//threesome2 /post/view Begins Here

//threesome2 /post/view Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//threesome3 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_threesome3 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//threesome3 /layout/pc_layout_miniblog/template Ends Here
?><?php
//threesome3 /default-layout Begins Here

//threesome3 /default-layout Ends Here
?><?php
//threesome3 /post/view Begins Here

//threesome3 /post/view Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome1 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_foursome1 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome1 /layout/pc_layout_miniblog/template Ends Here
?><?php
//foursome1 /default-layout Begins Here

//foursome1 /default-layout Ends Here
?><?php
//foursome1 /post/view Begins Here

//foursome1 /post/view Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome2 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_foursome2 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome2 /layout/pc_layout_miniblog/template Ends Here
?><?php
//foursome2 /default-layout Begins Here

//foursome2 /default-layout Ends Here
?><?php
//foursome2 /post/view Begins Here

//foursome2 /post/view Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-3 3u 6u(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//foursome3 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_foursome3 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome3 /layout/pc_layout_miniblog/template Ends Here
?><?php
//foursome3 /default-layout Begins Here

//foursome3 /default-layout Ends Here
?><?php
//foursome3 /post/view Begins Here

//foursome3 /post/view Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-3 3u 6u$(medium) 12u$(xsmall) 12u$(mobile)">    
												<?php
//foursome4 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_foursome4 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//foursome4 /layout/pc_layout_miniblog/template Ends Here
?><?php
//foursome4 /default-layout Begins Here

//foursome4 /default-layout Ends Here
?><?php
//foursome4 /post/view Begins Here

//foursome4 /post/view Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//leftbar /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_leftbar as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//leftbar /layout/pc_layout_miniblog/template Ends Here
?><?php
//leftbar /default-layout Begins Here

//leftbar /default-layout Ends Here
?><?php
//leftbar /post/view Begins Here

//leftbar /post/view Ends Here
?>
										   </div>
											<div class="pc_page_layout_grid col-sm-8 8u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//leftbarright /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_leftbarright as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//leftbarright /layout/pc_layout_miniblog/template Ends Here
?><?php
//leftbarright /default-layout Begins Here

//leftbarright /default-layout Ends Here
?><?php
//leftbarright /post/view Begins Here

//leftbarright /post/view Ends Here
?>
											</div> 
										</div> 
										<div class="row">
											<div class="pc_page_layout_grid col-sm-8 8u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//rightbarleft /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_rightbarleft as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//rightbarleft /layout/pc_layout_miniblog/template Ends Here
?><?php
//rightbarleft /default-layout Begins Here

//rightbarleft /default-layout Ends Here
?><?php
//rightbarleft /post/view Begins Here

					if( empty( $_871a4683bca92fa0998151c939f71ec1 ) || ! is_object( $_871a4683bca92fa0998151c939f71ec1 ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_871a4683bca92fa0998151c939f71ec1, '' );

					
//rightbarleft /post/view Ends Here
?>
											</div> 
											<div class="pc_page_layout_grid col-sm-4 4u 12u$(medium) 12u$(xsmall) 12u$(mobile)">
												<?php
//rightbar /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_rightbar as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//rightbar /layout/pc_layout_miniblog/template Ends Here
?><?php
//rightbar /default-layout Begins Here

//rightbar /default-layout Ends Here
?><?php
//rightbar /post/view Begins Here

//rightbar /post/view Ends Here
?>
											</div>   
										</div> 
									</div> 
									</section><?php
//lastoneness /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_lastoneness as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//lastoneness /layout/pc_layout_miniblog/template Ends Here
?><?php
//lastoneness /default-layout Begins Here

//lastoneness /default-layout Ends Here
?><?php
//lastoneness /post/view Begins Here

					if( empty( $_1ec416705cd18b9267d8b10cbe7c2851 ) || ! is_object( $_1ec416705cd18b9267d8b10cbe7c2851 ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_1ec416705cd18b9267d8b10cbe7c2851, '' );

					
					if( empty( $_10e0583681d44099c1a9e038384b653f ) || ! is_object( $_10e0583681d44099c1a9e038384b653f ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_10e0583681d44099c1a9e038384b653f, '' );

					
					if( empty( $_85c9419042cf5eb1948aad0e9e8aeb75 ) || ! is_object( $_85c9419042cf5eb1948aad0e9e8aeb75 ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_85c9419042cf5eb1948aad0e9e8aeb75, '' );

					
					if( empty( $_6dee86d34f712929d5fa8e80f452cdc8 ) || ! is_object( $_6dee86d34f712929d5fa8e80f452cdc8 ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_6dee86d34f712929d5fa8e80f452cdc8, 'well' );

					
					if( empty( $_547150e4df0861c8fe81c9b00f82114d ) || ! is_object( $_547150e4df0861c8fe81c9b00f82114d ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_547150e4df0861c8fe81c9b00f82114d, 'white-well' );

					
//lastoneness /post/view Ends Here
?>    

    <?php
//pc_body_4 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_pc_body_4 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//pc_body_4 /layout/pc_layout_miniblog/template Ends Here
?><?php
//pc_body_4 /default-layout Begins Here

					if( empty( $_f08919130e564f1d757a848674a358d7 ) || ! is_object( $_f08919130e564f1d757a848674a358d7 ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_f08919130e564f1d757a848674a358d7, '' );

					
//pc_body_4 /default-layout Ends Here
?><?php
//pc_body_4 /post/view Begins Here

//pc_body_4 /post/view Ends Here
?>

    <?php
//pc_body_5 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_pc_body_5 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//pc_body_5 /layout/pc_layout_miniblog/template Ends Here
?><?php
//pc_body_5 /default-layout Begins Here

//pc_body_5 /default-layout Ends Here
?><?php
//pc_body_5 /post/view Begins Here

//pc_body_5 /post/view Ends Here
?>

    <?php
//pc_body_6 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_pc_body_6 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//pc_body_6 /layout/pc_layout_miniblog/template Ends Here
?><?php
//pc_body_6 /default-layout Begins Here

//pc_body_6 /default-layout Ends Here
?><?php
//pc_body_6 /post/view Begins Here

//pc_body_6 /post/view Ends Here
?>

    <?php
//pc_body_7 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_pc_body_7 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//pc_body_7 /layout/pc_layout_miniblog/template Ends Here
?><?php
//pc_body_7 /default-layout Begins Here

//pc_body_7 /default-layout Ends Here
?><?php
//pc_body_7 /post/view Begins Here

//pc_body_7 /post/view Ends Here
?>

    <?php
//pc_body_8 /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_pc_body_8 as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
					if( empty( $_274f1f7e068d8ec9b8ec0a58942072c2 ) || ! is_object( $_274f1f7e068d8ec9b8ec0a58942072c2 ) )
					{
						//Ayoola_Page_Layout_Abstract::refreshThemePage(  );
					}
					echo Ayoola_Object_Wrapper_Abstract::wrap( $_274f1f7e068d8ec9b8ec0a58942072c2, '' );

					
//pc_body_8 /layout/pc_layout_miniblog/template Ends Here
?><?php
//pc_body_8 /default-layout Begins Here

//pc_body_8 /default-layout Ends Here
?><?php
//pc_body_8 /post/view Begins Here

//pc_body_8 /post/view Ends Here
?>

  </div>

  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/jquery-3.3.1.min.js"></script>
  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/jquery-migrate-3.0.1.min.js"></script>
  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/jquery-ui.js"></script>
  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/popper.min.js"></script>
  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/bootstrap.min.js"></script>
  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/owl.carousel.min.js"></script>
  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/jquery.stellar.min.js"></script>
  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/jquery.countdown.min.js"></script>
  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/jquery.magnific-popup.min.js"></script>
  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/bootstrap-datepicker.min.js"></script>
  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/aos.js"></script>

  <script src="<?php echo Ayoola_Application::getUrlPrefix(); ?>/layout/pc_layout_miniblog/js/main.js"></script>

  <?php include_once( LAYOUT_PATH . DS . 'footerJs' . TPL ) ?><?php include_once( LAYOUT_PATH . DS . 'footer' . TPL ) ?><?php
//pc_section_after_js /layout/pc_layout_miniblog/template Begins Here

                foreach( $_sitePageWidget_pc_section_after_js as $eachSitePageWidget )
                {
                    echo $eachSitePageWidget->view();
                }
                
//pc_section_after_js /layout/pc_layout_miniblog/template Ends Here
?><?php
//pc_section_after_js /default-layout Begins Here

//pc_section_after_js /default-layout Ends Here
?><?php
//pc_section_after_js /post/view Begins Here

//pc_section_after_js /post/view Ends Here
?>
</body>
</html>
