<?php echo Application_Javascript::getAll(); ?>
<?php echo Application_Style::getAll(); ?>
<?php if( Application_Settings_CompanyInfo::getSettings( 'SocialMedia', 'google_analytics_tracking_id' ) )
{
//	echo Application_Settings_CompanyInfo::getSettings( 'SocialMedia', 'google_analytics_tracking_id' );
?>
<script>
	//	Google Analytics
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<?php echo Application_Settings_CompanyInfo::getSettings( 'SocialMedia', 'google_analytics_tracking_id' ); ?>', 'auto');
  ga('send', 'pageview');

</script>
<?php 
}
?>
